version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: userDB
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_PASSWORD=1981
      - POSTGRES_USER=denmit
      - POSTGRES_DB=userdb
